/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package eventmanagementsystem;

import com.formdev.flatlaf.FlatLightLaf;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Ren
 */
public class frmHome extends javax.swing.JFrame {

    /**
     * Creates new form frmHome
     */
    public frmHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        pnlHomeLeft = new javax.swing.JPanel();
        pnlHeader = new javax.swing.JPanel();
        txtHeader = new javax.swing.JLabel();
        pnlManagBtns = new javax.swing.JPanel();
        btnVenues = new javax.swing.JButton();
        btnEvents = new javax.swing.JButton();
        pnlExitBtn = new javax.swing.JPanel();
        txtCredit = new javax.swing.JLabel();
        btnExit = new javax.swing.JButton();
        pnlHomeRight = new javax.swing.JPanel();
        pnlHomeBckgrnd = new javax.swing.JPanel();
        imgBackground = new javax.swing.JLabel();
        pnlHomeReg = new javax.swing.JPanel();
        btnAttendees = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(100, 112, 143));
        setMaximumSize(new java.awt.Dimension(700, 350));
        setMinimumSize(new java.awt.Dimension(700, 350));
        setName("frmHome"); // NOI18N
        setSize(new java.awt.Dimension(700, 350));

        pnlHomeLeft.setBackground(new java.awt.Color(100, 112, 143));
        pnlHomeLeft.setMaximumSize(new java.awt.Dimension(250, 350));
        pnlHomeLeft.setMinimumSize(new java.awt.Dimension(250, 350));
        pnlHomeLeft.setOpaque(false);
        pnlHomeLeft.setPreferredSize(new java.awt.Dimension(250, 350));
        pnlHomeLeft.setLayout(new java.awt.BorderLayout());

        pnlHeader.setBackground(new java.awt.Color(23, 42, 85));
        pnlHeader.setForeground(new java.awt.Color(204, 204, 204));
        pnlHeader.setMaximumSize(new java.awt.Dimension(300, 100));
        pnlHeader.setMinimumSize(new java.awt.Dimension(300, 100));
        pnlHeader.setPreferredSize(new java.awt.Dimension(300, 100));
        pnlHeader.setRequestFocusEnabled(false);
        pnlHeader.setLayout(new java.awt.BorderLayout());

        txtHeader.setBackground(new java.awt.Color(204, 204, 204));
        txtHeader.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtHeader.setForeground(new java.awt.Color(204, 204, 204));
        txtHeader.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtHeader.setText("Event Management System");
        txtHeader.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pnlHeader.add(txtHeader, java.awt.BorderLayout.CENTER);

        pnlHomeLeft.add(pnlHeader, java.awt.BorderLayout.NORTH);

        pnlManagBtns.setBackground(new java.awt.Color(100, 112, 143));
        pnlManagBtns.setForeground(new java.awt.Color(0, 0, 0));
        pnlManagBtns.setMaximumSize(new java.awt.Dimension(300, 150));
        pnlManagBtns.setMinimumSize(new java.awt.Dimension(300, 150));
        pnlManagBtns.setName(""); // NOI18N
        pnlManagBtns.setPreferredSize(new java.awt.Dimension(300, 150));
        java.awt.GridBagLayout jPanel6Layout = new java.awt.GridBagLayout();
        jPanel6Layout.columnWidths = new int[] {0, 5, 0};
        jPanel6Layout.rowHeights = new int[] {0, 6, 0, 6, 0, 6, 0};
        pnlManagBtns.setLayout(jPanel6Layout);

        btnVenues.setBackground(new java.awt.Color(204, 204, 204));
        btnVenues.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnVenues.setForeground(new java.awt.Color(0, 0, 0));
        btnVenues.setText("Manage Venues");
        btnVenues.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnVenues.setPreferredSize(new java.awt.Dimension(150, 30));
        btnVenues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVenuesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        pnlManagBtns.add(btnVenues, gridBagConstraints);

        btnEvents.setBackground(new java.awt.Color(204, 204, 204));
        btnEvents.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnEvents.setForeground(new java.awt.Color(0, 0, 0));
        btnEvents.setText("Manage Events");
        btnEvents.setPreferredSize(new java.awt.Dimension(150, 30));
        btnEvents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventsActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTH;
        pnlManagBtns.add(btnEvents, gridBagConstraints);

        pnlHomeLeft.add(pnlManagBtns, java.awt.BorderLayout.CENTER);

        pnlExitBtn.setBackground(new java.awt.Color(100, 112, 143));
        pnlExitBtn.setPreferredSize(new java.awt.Dimension(250, 100));
        java.awt.GridBagLayout jPanel3Layout = new java.awt.GridBagLayout();
        jPanel3Layout.columnWidths = new int[] {0};
        jPanel3Layout.rowHeights = new int[] {0, 6, 0, 6, 0, 6, 0};
        pnlExitBtn.setLayout(jPanel3Layout);

        txtCredit.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        txtCredit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtCredit.setText("Hendrik Zwiegelaar 2024");
        txtCredit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        pnlExitBtn.add(txtCredit, gridBagConstraints);

        btnExit.setBackground(new java.awt.Color(153, 153, 153));
        btnExit.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(0, 0, 0));
        btnExit.setText("Exit");
        btnExit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExit.setMaximumSize(new java.awt.Dimension(150, 30));
        btnExit.setMinimumSize(new java.awt.Dimension(150, 30));
        btnExit.setPreferredSize(new java.awt.Dimension(150, 30));
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        pnlExitBtn.add(btnExit, gridBagConstraints);

        pnlHomeLeft.add(pnlExitBtn, java.awt.BorderLayout.SOUTH);

        getContentPane().add(pnlHomeLeft, java.awt.BorderLayout.LINE_START);

        pnlHomeRight.setBackground(new java.awt.Color(100, 112, 143));
        pnlHomeRight.setMaximumSize(new java.awt.Dimension(450, 350));
        pnlHomeRight.setMinimumSize(new java.awt.Dimension(450, 350));
        pnlHomeRight.setPreferredSize(new java.awt.Dimension(450, 350));
        pnlHomeRight.setLayout(new java.awt.BorderLayout());

        pnlHomeBckgrnd.setMaximumSize(new java.awt.Dimension(450, 350));
        pnlHomeBckgrnd.setMinimumSize(new java.awt.Dimension(450, 350));
        pnlHomeBckgrnd.setName(""); // NOI18N
        pnlHomeBckgrnd.setPreferredSize(new java.awt.Dimension(450, 250));
        pnlHomeBckgrnd.setLayout(new java.awt.BorderLayout());

        imgBackground.setBackground(new java.awt.Color(23, 42, 85));
        imgBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/background 1.jpg"))); // NOI18N
        imgBackground.setIconTextGap(0);
        pnlHomeBckgrnd.add(imgBackground, java.awt.BorderLayout.CENTER);

        pnlHomeRight.add(pnlHomeBckgrnd, java.awt.BorderLayout.NORTH);

        pnlHomeReg.setBackground(new java.awt.Color(0, 0, 0));
        pnlHomeReg.setPreferredSize(new java.awt.Dimension(450, 100));

        btnAttendees.setBackground(new java.awt.Color(100, 112, 143));
        btnAttendees.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        btnAttendees.setForeground(new java.awt.Color(0, 0, 0));
        btnAttendees.setText("Register for an event");
        btnAttendees.setMargin(new java.awt.Insets(2, 14, 2, 14));
        btnAttendees.setMaximumSize(new java.awt.Dimension(150, 30));
        btnAttendees.setMinimumSize(new java.awt.Dimension(150, 30));
        btnAttendees.setOpaque(true);
        btnAttendees.setPreferredSize(new java.awt.Dimension(180, 40));
        btnAttendees.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendeesActionPerformed(evt);
            }
        });
        pnlHomeReg.add(btnAttendees);

        pnlHomeRight.add(pnlHomeReg, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnlHomeRight, java.awt.BorderLayout.LINE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEventsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventsActionPerformed
        frmEvents events = new frmEvents();
        events.setLocationRelativeTo(null);
        events.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnEventsActionPerformed

    private void btnAttendeesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendeesActionPerformed
        frmAttendees attendees = new frmAttendees();
        attendees.setLocationRelativeTo(null);
        attendees.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnAttendeesActionPerformed

    private void btnVenuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVenuesActionPerformed
        frmVenues venues = new frmVenues();
        venues.setLocationRelativeTo(null);
        venues.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnVenuesActionPerformed

    /**
     * @param args the command line arguments
     */
   

        /* Create and display the form */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttendees;
    private javax.swing.JButton btnEvents;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnVenues;
    private javax.swing.JLabel imgBackground;
    private javax.swing.JPanel pnlExitBtn;
    private javax.swing.JPanel pnlHeader;
    private javax.swing.JPanel pnlHomeBckgrnd;
    private javax.swing.JPanel pnlHomeLeft;
    private javax.swing.JPanel pnlHomeReg;
    private javax.swing.JPanel pnlHomeRight;
    private javax.swing.JPanel pnlManagBtns;
    private javax.swing.JLabel txtCredit;
    private javax.swing.JLabel txtHeader;
    // End of variables declaration//GEN-END:variables
}
